Validating audit models too

diff --git a/.github/workflows/validate-migrations.yml b/.github/workflows/validate-migrations.yml
--- a/.github/workflows/validate-migrations.yml
+++ b/.github/workflows/validate-migrations.yml
@@ -5,7 +5,7 @@ permissions:
 
 on:
   workflow_call:
-    
+
 jobs:
   validate-migrations:
     runs-on: ubuntu-latest
@@ -36,5 +36,10 @@ jobs:
           # --dry-run: Doesn't actually create the files
           if ! python manage.py makemigrations --check --dry-run dissemination; then
             echo "::error title=Missing Migrations Detected::It looks like you've changed the models in 'dissemination' but haven't added the corresponding migration file(s) that are generated. Look for newly created files with a path similar to 'backend/dissemination/migrations/####_foo.py'."
+            exit 1
+          fi
+
+          if ! python manage.py makemigrations --check --dry-run audit; then
+            echo "::error title=Missing Migrations Detected::It looks like you've changed the models in 'audit' but haven't added the corresponding migration file(s) that are generated. Look for newly created files with a path similar to 'backend/audit/migrations/####_foo.py'."
             exit 1
           fi
